describe('Страница связного списка', () => {
    beforeEach(() => {
        cy.visit("/list")
        cy.get('input[id="text"]').as('text')
        cy.get('input[id="index"]').as('index')
        cy.get('button[id="prepend"]').as('prepend')
        cy.get('button[id="append"]').as('append')
        cy.get('button[id="deleteHead"]').as('deleteHead')
        cy.get('button[id="deleteTail"]').as('deleteTail')
        cy.get('button[id="addByIndex"]').as('addByIndex')
        cy.get('button[id="deleteByIndex"]').as('deleteByIndex')
        cy.get('#solution > div').as('circles')
    })
    it('Проверка инактивности кнопок', () => {
        cy.get('@text').clear()
        cy.get('@index').clear()
        cy.get('@prepend').should('be.disabled')
        cy.get('@append').should('be.disabled')
        cy.get('@addByIndex').should('be.disabled')
        cy.get('@deleteByIndex').should('be.disabled')
    })
    it('Проверка правильности отрисовки базового списка', () => {
        cy.get('@circles').should('exist')
    })
    it('Проверка добавления элемента в head', () => {
        cy.get('@text').type('head')
        cy.get('@prepend').click()
        cy.wait(500)
        cy.get('@circles').first().find('.text_type_circle').should('have.text', 'head')
    })
    it('Проверка добавления элемента в tail', () => {
        cy.get('@text').type('tail')
        cy.get('@append').click()
        cy.wait(500)
        cy.get('@circles').last().find('.text_type_circle').should('have.text', 'tail')
    })
    it('Проверка удаления элемента из head', () => {
        cy.get('@text').type('head')
        cy.get('@prepend').click()
        cy.wait(1000)
        cy.get('@circles').first().find('.text_type_circle').should('have.text', 'head')
        cy.get('@deleteHead').click()
        cy.wait(1000)
        cy.get('@circles').first().find('.text_type_circle').should('not.have.text', 'head')
    })
    it('Проверка удаления элемента из tail', () => {
        cy.get('@text').type('tail')
        cy.get('@append').click()
        cy.wait(1000)
        cy.get('@circles').last().find('.text_type_circle').should('have.text', 'tail')
        cy.get('@deleteTail').click()
        cy.wait(1000)
        cy.get('@circles').last().find('.text_type_circle').should('not.have.text', 'tail')
    })
    it('Проверка добавления элемента по индексу', () => {
        cy.get('@text').type('Find')
        cy.get('@index').type('1')
        cy.get('@addByIndex').click()
        cy.wait(1000)
        cy.get('@circles').eq(1).find('.text_type_circle').should('have.text', 'Find')
    })
    it('Проверка удаления элемента по индексу', () => {
        cy.get('@text').type('Kek')
        cy.get('@index').type('2')
        cy.get('@addByIndex').click()
        cy.get('@circles').eq(2).find('.text_type_circle').should('have.text', 'Kek')
        cy.get('@index').clear()
        cy.get('@index').type('2')
        cy.get('@deleteByIndex').click()
        cy.wait(3000)
        cy.get('@circles').eq(3).find('.text_type_circle').should('not.have.text', 'Kek')
    })
})