describe('Страница стек', () => {
    beforeEach(() => {
        cy.visit('/stack')
    })
    it('Проверка инактивности кнопок', () => {
        cy.get('input').clear()
        cy.get('button[id="submit"]').should('be.disabled')
        cy.get('button[id="delete"]').should('be.disabled')
        cy.get('button[id="clear"]').should('be.disabled')
    })
    it('Проверка функции добавления в стек', () => {
        cy.get('input').type(1)
        cy.get('button[id="submit"]').click()
        cy.get('ul[id="solution"] > div').as('circles')
        cy.get('@circles').should('have.length', 1)
        cy.get('@circles').last().find('div[class*="circle_changing"]')
        cy.wait(500)
        cy.get('@circles').last().find('div[class*="circle_default"]')
        cy.get('#solution .text_type_circle').last().should('have.text', 1)
        cy.get('input').type(2)
        cy.get('button[id="submit"]').click()
        cy.wait(500)
        cy.get('@circles').should('have.length', 2)
        cy.get('button[id="clear"]').click()
    })
    it('Проверка функции удаления из стека', () => {
        cy.get('input').type(1)
        cy.get('button[id="submit"]').click()
        cy.wait(500)
        cy.get('input').type(5)
        cy.get('button[id="submit"]').click()
        cy.wait(500)
        cy.get('ul[id="solution"] > div').as('circles')
        cy.get('@circles').should('have.length', 2)
        cy.get('button[id="delete"]').click()
        cy.wait(500)
        cy.get('@circles').should('have.length', 1)
    })
    it('Проверка функции очистки стека', () => {
        cy.get('input').type(1)
        cy.get('button[id="submit"]').click()
        cy.wait(500)
        cy.get('input').type(5)
        cy.get('button[id="submit"]').click()
        cy.wait(500)
        cy.get('input').type(8)
        cy.get('button[id="submit"]').click()
        cy.wait(500)
        cy.get('ul[id="solution"] > div').as('circles')
        cy.get('@circles').should('have.length', 3)
        cy.get('button[id="clear"]').click()
        cy.get('@circles').should('have.length', 0)
    })
})